---
- name: BIG-IP SETUP
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

  - name: CREATE POOL
    bigip_pool:
      server: "{{f5_ip}}"
      user: "{{user}}"
      password: "{{password}}"
      server_port: "8443"
      name: "{{ pool_name }}"
      lb_method: "round-robin"
      monitors: "/Common/http"
      monitor_type: "and_list"
      validate_certs: "no"
    register: pool_created

  - name: ADD POOL MEMBERS
    bigip_pool_member:
      server: "{{f5_ip}}"
      user: "{{user}}"
      password: "{{password}}"
      server_port: "8443"
      state: "present"
      name: "{{hostname}}"
      host: "{{host}}"
      port: "80"
      pool: "{{ pool_name }}"
      validate_certs: "no"
    register: member_added
  
  - name: ADD VIRTUAL SERVER
    bigip_virtual_server:
      server: "{{f5_ip}}"
      user: "{{user}}"
      password: "{{password}}"
      server_port: "8443"
      name: "{{ vs_name }}"
      destination: "{{f5_ip}}"
      port: "443"
      enabled_vlans: "all"
      all_profiles: ['http','clientssl','oneconnect']
      pool: "{{ pool_name }}"
      snat: "Automap"
      validate_certs: "no"
   register: virtual_server

  - name: CREATE NODES
    bigip_node:
      server: "{{f5_ip}}"
      user: "{{user}}"
      password: "{{password}}"
      server_port: "8443"
      host: "{{ host }}"
      name: "{{ hostname }}"
      validate_certs: "no"
    register: node_created
